config:
  name: XDE
  shortname: xde
  description: 'Exponent Development Environment'
  depends_on:
    - xdl
  regions:
    - dev/xde/**

steps:
  - name: 'Build XDE / Mac'
    command: sleep 0
    agents:
      mac: "true"

  - name: 'Build XDE / Windows'
    command: sleep 0
    agents:
      windows: "true"

  - name: 'Build XDE / Linux'
    command: sleep 0
    agents:
      linux: "true"
